### PR TITLE
Fix typos in section labels in index.html

### PR DESCRIPTION
**Pull request by arilivigni**
This PR corrects several instances of the typo "Sapmle" to "Sample" in the section labels of index.html. This ensures that the labels accurately reflect the content of the sections.

### CODE REVIEW

**Review by vfm2 — APPROVED** [review]
LGTM 👍

**Comment by arilivigni** [comment]
@jefeish just need your review and this can be merged

**Review by jefeish — APPROVED** [review]
so much for "copy & paste" 😄

**Comment by jefeish** [comment]
I'll feep the `fix-spelling` branch open ...since I feel there is gonna be more 😬

**Pull request merged**
